# Generated by Django 3.0.8 on 2020-09-25 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_0', to=settings.AUTH_USER_MODEL)),
                ('member_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_1', to=settings.AUTH_USER_MODEL)),
                ('member_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_2', to=settings.AUTH_USER_MODEL)),
                ('member_3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_3', to=settings.AUTH_USER_MODEL)),
                ('member_4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_4', to=settings.AUTH_USER_MODEL)),
                ('member_5', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_5', to=settings.AUTH_USER_MODEL)),
                ('member_6', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_6', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank='False')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank='False', on_delete=django.db.models.deletion.PROTECT, related_name='author_id', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(blank='False', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
