# Generated by Django 3.0.8 on 2020-09-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0002_auto_20200925_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_id', to='core_backend.Rooms'),
        ),
    ]
